### ISSUE TITLE
Manual Crop

### ISSUE THREAD

**Issue by ivanpetrovic** [globocom/thumbor-client-ex#1]
Hi,

Is there a way to do a manual crop ?
I can't find any reference to manual cropping in the Elixir client.

Thanks

**Comment by renatocassino** [comment]
What do you mean by "manual crop"? Is about choose the width and height?
If is this, there is an example in Readme

```
ThumborClient.generate(%{image: "image.jpg", width: 300, height: 200}, "my_secret_token")
```

**Comment by ivanpetrovic** [comment]
Hi,
No, I am referring to this
https://thumbor.readthedocs.io/en/latest/usage.html#manual-crop

This is done by specifying the coordinates for the upper left and lower right corner of the cropping rectangle.

**Comment by renatocassino** [comment]
I didn't make this implementation yet :/ @ivanpetrovic

**Comment by ivanpetrovic** [comment]
I have an implementation ready.
Can I do a pull request ?

**Comment by renatocassino** [comment]
Of course, please :D
